"""delete slug

Revision ID: 23e104a42774
Revises: cb2aca7719f7
Create Date: 2025-03-31 15:17:24.183658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23e104a42774'
down_revision: Union[str, None] = 'cb2aca7719f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('books_slug_key', 'books', type_='unique')
    op.drop_column('books', 'slug')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('slug', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_unique_constraint('books_slug_key', 'books', ['slug'])
    # ### end Alembic commands ###
