"""add slug to book

Revision ID: cb2aca7719f7
Revises: 4f6d586e2e62
Create Date: 2025-03-31 14:35:54.604634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb2aca7719f7'
down_revision: Union[str, None] = '4f6d586e2e62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('slug', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'books', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='unique')
    op.drop_column('books', 'slug')
    # ### end Alembic commands ###
