"""delete unique

Revision ID: dda412398e5c
Revises: 23e104a42774
Create Date: 2025-03-31 15:19:00.214841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dda412398e5c'
down_revision: Union[str, None] = '23e104a42774'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('books_title_key', 'books', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('books_title_key', 'books', ['title'])
    # ### end Alembic commands ###
